FROM node:20-alpine

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY . .


RUN pnpm install --frozen-lockfile

RUN pnpm --filter backend exec prisma generate 

RUN pnpm --filter backend build

EXPOSE 8001

CMD ["pnpm","--filter","backend", "start"]
