FROM node:20-alpine

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY . .


RUN pnpm install --frozen-lockfile

RUN pnpm --filter ws build

EXPOSE 8080

CMD ["pnpm","--filter","ws", "start"]
